# Build settings
[build]
  publish = "dist"
  command = "npm install && npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "18.17.0"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200